import { useCallback, useEffect, useRef, useState } from 'react';
import { Terminal } from 'xterm';
import { FitAddon } from 'xterm-addon-fit';
import 'xterm/css/xterm.css';
import { api, TerminalSession, WatchTarget } from './client';

type Module = 'dashboard' | 'watchlist' | 'ap' | 'terminal';
type Device = { ip: string; mac: string; type: string };
type Overview = { timestamp?: string; adapters: Array<{ name: string; rxBytesPerSec: number; txBytesPerSec: number }>; activeAdapters: number; addresses: number; protocolBreakdown: Array<{ protocol: string; connections: number; bytesPerSec: number }>; activeIps: Array<{ ip: string; connections: number; bytesPerSec: number }> };
const emptyOverview: Overview = { adapters: [], activeAdapters: 0, addresses: 0, protocolBreakdown: [], activeIps: [] };
const navItems: Array<{ id: Module; label: string; icon: string }> = [
  { id: 'dashboard', label: 'Dashboard', icon: '⌂' }, { id: 'watchlist', label: 'IP Watchlist', icon: '◉' },
  { id: 'ap', label: 'AP Monitor', icon: '⌁' }, { id: 'terminal', label: 'Terminal Sessions', icon: '›_' },
];
const fmtRate = (value: number) => value > 1_000_000 ? `${(value / 1_000_000).toFixed(1)} MB/s` : value > 1_000 ? `${(value / 1_000).toFixed(1)} KB/s` : `${Math.round(value)} B/s`;

function App() {
  const [module, setModule] = useState<Module>('dashboard');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [online, setOnline] = useState(true);
  const [lastRefresh, setLastRefresh] = useState(new Date());
  const [overview, setOverview] = useState<Overview>(emptyOverview);
  const [search, setSearch] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const refresh = useCallback(async () => {
    try {
      const data = await api.getOverview();
      const adapters = Array.isArray(data.adapters) ? data.adapters : [];
      setOverview({ ...emptyOverview, ...data, adapters, protocolBreakdown: Array.isArray(data.protocolBreakdown) ? data.protocolBreakdown : [], activeIps: Array.isArray(data.activeIps) ? data.activeIps : [] });
      setOnline(true);
    } catch { setOnline(false); }
    setLastRefresh(new Date());
  }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, [refresh]);
  useEffect(() => { if (!search.trim()) { setSearchResults([]); return; } const timer = window.setTimeout(() => { void api.search(search).then(setSearchResults).catch(() => setSearchResults([])); }, 250); return () => window.clearTimeout(timer); }, [search]);
  return <div className={`app-shell ${sidebarOpen ? '' : 'sidebar-collapsed'}`}>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>sentinel</strong><span>NETWORK OPS</span></div></div><div className="workspace-label">WORKSPACE</div><nav>{navItems.map((item) => <button key={item.id} className={module === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setModule(item.id)}><span className="nav-icon">{item.icon}</span><span className="nav-label">{item.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="status-line"><span className={`status-dot ${online ? '' : 'offline'}`} />{online ? 'Agent connected' : 'Agent unavailable'}</div><small>v0.1.0 · Local workspace</small></div></aside>
    <main className="main"><header className="topbar"><div className="topbar-title"><button className="icon-button menu-button" onClick={() => setSidebarOpen((open) => !open)} aria-label="Toggle navigation">☰</button><div><div className="eyebrow">NETWORK OPERATIONS / {module.toUpperCase()}</div><h1>{navItems.find((item) => item.id === module)?.label}</h1></div></div><div className="top-actions"><div className="search-wrap"><input aria-label="Search devices, targets and sessions" placeholder="Search…" value={search} onChange={(event) => setSearch(event.target.value)} />{searchResults.length > 0 && <div className="search-results">{searchResults.slice(0, 6).map((item) => <button key={`${item.type}-${item.id}`} onClick={() => { setModule(item.type === 'session' ? 'terminal' : item.type === 'target' ? 'watchlist' : 'dashboard'); setSearch(''); }}><b>{item.title}</b><span>{item.type} · {item.detail}</span></button>)}</div>}</div><span className="updated">Updated {lastRefresh.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</span><button className="icon-button" onClick={() => void refresh()} aria-label="Refresh">↻</button><div className="avatar">SK</div></div></header>
      {module === 'dashboard' && <Dashboard overview={overview} online={online} onNavigate={setModule} />}
      {module === 'watchlist' && <Watchlist />}
      {module === 'ap' && <AccessPoints />}
      {module === 'terminal' && <TerminalSessions />}
    </main>
  </div>;
}

function Dashboard({ overview, online, onNavigate }: { overview: Overview; online: boolean; onNavigate: (module: Module) => void }) {
  const [devices, setDevices] = useState<Device[]>([]);
  const [scanning, setScanning] = useState(false);
  const scan = async () => { setScanning(true); try { setDevices(await api.discoverArp()); } catch { setDevices([]); } setScanning(false); };
  useEffect(() => { void scan(); }, []);
  const totalRx = overview.adapters.reduce((sum, item) => sum + item.rxBytesPerSec, 0);
  const totalTx = overview.adapters.reduce((sum, item) => sum + item.txBytesPerSec, 0);
  return <div className="content"><section className="hero-row"><div><p className="muted">Live network telemetry</p><h2>Your network at a glance.</h2></div><div className="button-row"><a className="secondary button-link" href={api.exportUrl('network', 'json')}>Export JSON</a><a className="secondary button-link" href={api.exportUrl('network', 'csv')}>Export CSV</a><button className="primary" onClick={() => void scan()}>{scanning ? 'Scanning…' : '＋ Run discovery'}</button></div></section>
    <div className="metric-grid"><Metric label="Monitored devices" value={String(devices.length)} trend={`${overview.activeIps.length} active IPs`} icon="⌁" tone="blue" /><Metric label="Availability" value={online ? 'Online' : 'Offline'} trend={online ? 'Live polling active' : 'API unavailable'} icon="✓" tone="green" /><Metric label="Traffic now" value={fmtRate(totalRx + totalTx)} trend={`↓ ${fmtRate(totalRx)} · ↑ ${fmtRate(totalTx)}`} icon="!" tone="amber" /><Metric label="Interfaces" value={`${overview.activeAdapters}/${overview.adapters.length}`} trend={`${overview.addresses} addresses`} icon="◌" tone="purple" /></div>
    <div className="section-grid"><section className="panel wide"><div className="panel-heading"><div><h3>Traffic overview</h3><span className="muted">Per-interface receive and transmit rates · live</span></div></div><TrafficChart adapters={overview.adapters} /></section><section className="panel"><div className="panel-heading"><div><h3>Protocol breakdown</h3><span className="muted">Active connections</span></div></div>{overview.protocolBreakdown.length ? overview.protocolBreakdown.map((item) => <div className="data-row" key={item.protocol}><b>{item.protocol}</b><span>{item.connections} connections</span><strong>{fmtRate(item.bytesPerSec)}</strong></div>) : <div className="empty">Connection data is not available on this platform.</div>}</section></div>
    <div className="section-grid"><section className="panel"><div className="panel-heading"><div><h3>Active IP bandwidth</h3><span className="muted">Connection-level activity</span></div></div>{overview.activeIps.length ? overview.activeIps.slice(0, 8).map((item) => <div className="data-row" key={item.ip}><b className="mono">{item.ip}</b><span>{item.connections} connections</span><strong>{fmtRate(item.bytesPerSec)}</strong></div>) : <div className="empty">No active remote IPs.</div>}</section><section className="panel"><div className="panel-heading"><div><h3>Discovered devices</h3><span className="muted">ARP / native table discovery</span></div><button className="text-button" onClick={() => onNavigate('ap')}>Open monitor →</button></div><DeviceTable devices={devices} /></section></div>
  </div>;
}
function Metric({ label, value, trend, icon, tone }: { label: string; value: string; trend: string; icon: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span className="metric-label">{label}</span><strong>{value}</strong><span className={`metric-trend ${tone}`}>{trend}</span></div>; }
function TrafficChart({ adapters }: { adapters: Overview['adapters'] }) { const values = adapters.length ? adapters.map((item) => item.rxBytesPerSec + item.txBytesPerSec) : [0]; const max = Math.max(...values, 1); return <div className="chart"><div className="chart-y"><span>Max</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div><div className="chart-body"><div className="grid-lines">{[1, 2, 3, 4].map((line) => <i key={line} />)}</div><div className="bars">{values.map((value, index) => <div className="bar-wrap" key={adapters[index]?.name || index}><div className="bar" title={`${adapters[index]?.name || 'traffic'}: ${fmtRate(value)}`} style={{ height: `${Math.max(4, value / max * 100)}%` }} /></div>)}</div><div className="chart-x">{adapters.map((item) => <span key={item.name}>{item.name}</span>)}</div></div></div>; }
function DeviceTable({ devices }: { devices: Device[] }) { return <div className="table-wrap"><table><thead><tr><th>IP ADDRESS</th><th>MAC ADDRESS</th><th>TYPE</th><th>STATUS</th></tr></thead><tbody>{(devices.length ? devices.slice(0, 8) : [{ ip: '—', mac: 'No devices found', type: '—' }]).map((device, index) => <tr key={device.ip}><td><span className="device-dot" />{device.ip}</td><td className="mono">{device.mac}</td><td>{device.type}</td><td><span className={device.ip === '—' ? 'pill muted-pill' : 'pill green-pill'}>{device.ip === '—' ? '—' : index === 0 ? 'Gateway' : 'Reachable'}</span></td></tr>)}</tbody></table></div>; }

function Watchlist() {
  const [targets, setTargets] = useState<WatchTarget[]>([]); const [form, setForm] = useState({ value: '', label: '', latencyThreshold: '250' }); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setTargets(await api.getWatchlist()); } catch { setTargets([]); } }, []);
  useEffect(() => { void load(); }, [load]);
  const add = async () => { if (!form.value.trim()) return; setBusy(true); try { await api.addWatch({ value: form.value, label: form.label, latencyThreshold: Number(form.latencyThreshold), enabled: true }); setForm({ value: '', label: '', latencyThreshold: '250' }); await load(); } finally { setBusy(false); } };
  const check = async () => { setBusy(true); try { setTargets(await api.checkWatchlist()); } finally { setBusy(false); } };
  const remove = async (id: string) => { await api.deleteWatch(id); setTargets((items) => items.filter((item) => item._id !== id)); };
  const toggle = async (target: WatchTarget) => { const updated = await api.updateWatch(target._id, { enabled: !target.enabled }); setTargets((items) => items.map((item) => item._id === target._id ? updated : item)); };
  const edit = (target: WatchTarget, field: 'label' | 'latencyThreshold', value: string) => { const updated = { ...target, [field]: field === 'latencyThreshold' ? Number(value) || 250 : value }; setTargets((items) => items.map((item) => item._id === target._id ? updated : item)); void api.updateWatch(target._id, { [field]: updated[field] } as Partial<WatchTarget>); };
  return <div className="content"><section className="hero-row"><div><p className="muted">ICMP checks with latency thresholds</p><h2>Know what is up.</h2></div><div className="button-row"><a className="secondary button-link" href={api.exportUrl('watchlist', 'csv')}>Export CSV</a><button className="primary" onClick={() => void check()}>{busy ? 'Checking…' : '▶ Check all'}</button></div></section><div className="watch-layout"><section className="panel"><div className="panel-heading"><div><h3>Add watch target</h3><span className="muted">Checks run automatically every 30 seconds</span></div></div><label>HOST OR IP<input value={form.value} onChange={(event) => setForm({ ...form, value: event.target.value })} placeholder="192.168.1.10" /></label><label>LABEL<input value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder="Core router" /></label><label>LATENCY THRESHOLD (MS)<input value={form.latencyThreshold} onChange={(event) => setForm({ ...form, latencyThreshold: event.target.value })} inputMode="numeric" /></label><button className="secondary full" onClick={() => void add()}>{busy ? 'Saving…' : 'Add to watchlist'}</button></section><section className="panel"><div className="panel-heading"><div><h3>Monitored targets</h3><span className="muted">{targets.length} targets · edit status and thresholds</span></div></div>{targets.length ? targets.map((target) => <div className="watch-row" key={target._id}><button className="status-toggle" onClick={() => void toggle(target)} aria-label="Toggle target"><span className={`status-dot ${target.status === 'offline' ? 'offline' : ''}`} /></button><div className="watch-name"><input className="watch-edit" value={target.label || ''} placeholder={target.value} onChange={(event) => setTargets((items) => items.map((item) => item._id === target._id ? { ...item, label: event.target.value } : item))} onBlur={(event) => void edit(target, 'label', event.target.value)} /><span className="mono">{target.value}</span></div><span className="ping-time">{target.latency == null ? '—' : `${target.latency} ms`} <input className="threshold-edit" type="number" value={target.latencyThreshold} onChange={(event) => setTargets((items) => items.map((item) => item._id === target._id ? { ...item, latencyThreshold: Number(event.target.value) || 250 } : item))} onBlur={(event) => void edit(target, 'latencyThreshold', event.target.value)} /> ms</span><span className={`pill ${target.status === 'offline' ? 'red-pill' : target.status === 'degraded' ? 'amber-pill' : 'green-pill'}`}>{target.status || 'unknown'}</span><button className="delete-button" onClick={() => void remove(target._id)} aria-label={`Remove ${target.value}`}>×</button></div>) : <div className="empty">Add an IP or hostname to begin monitoring.</div>}</section></div></div>;
}

function AccessPoints() {
  const [host, setHost] = useState('192.168.1.1'); const [community, setCommunity] = useState('public'); const [oids, setOids] = useState('1.3.6.1.2.1.1.1.0\n1.3.6.1.2.1.1.3.0'); const [ports, setPorts] = useState('22,80,443'); const [result, setResult] = useState<Array<{ oid: string; value: string | number }>>([]); const [portResult, setPortResult] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const poll = async () => { setBusy(true); try { setResult(await api.pollSnmp({ host, community, oids: oids.split(/[\s,]+/).filter(Boolean), timeout: 2000 })); const status = await api.checkPorts(host, ports.split(/[\s,]+/).map(Number).filter(Boolean)); setPortResult(status.ports); } catch (error) { setResult([{ oid: 'error', value: error instanceof Error ? error.message : 'SNMP request failed' }]); } finally { setBusy(false); } };
  return <div className="content"><section className="hero-row"><div><p className="muted">SNMP metrics and TCP service health</p><h2>AP monitor.</h2></div><span className="chip"><span className="status-dot" />Configurable OIDs</span></section><div className="ap-grid"><section className="panel"><div className="panel-heading"><div><h3>SNMP poll</h3><span className="muted">SNMP v2c · provide one OID per line</span></div></div><label>HOST<input value={host} onChange={(event) => setHost(event.target.value)} /></label><label>COMMUNITY<input value={community} onChange={(event) => setCommunity(event.target.value)} /></label><label>OIDS<textarea className="small-textarea" value={oids} onChange={(event) => setOids(event.target.value)} /></label><label>TCP PORTS<input value={ports} onChange={(event) => setPorts(event.target.value)} /></label><button className="secondary full" onClick={() => void poll()}>{busy ? 'Polling…' : 'Poll metrics & ports'}</button></section><section className="panel"><div className="panel-heading"><div><h3>Access point health</h3><span className="muted">Live service status for {host}</span></div></div>{portResult.length ? portResult.map((item) => <div className="data-row" key={item.port}><b>TCP {item.port}</b><span /><span className={`pill ${item.reachable ? 'green-pill' : 'red-pill'}`}>{item.reachable ? 'Open' : 'Closed'}</span></div>) : <div className="empty">Poll the device to check configured services.</div>}</section></div>{result.length > 0 && <section className="panel result-panel"><div className="panel-heading"><h3>SNMP response</h3><span className="muted">{result.length} metrics</span></div>{result.map((item) => <div className="snmp-row" key={item.oid}><span className="mono">{item.oid}</span><span>{String(item.value)}</span></div>)}</section>}</div>;
}

function TerminalSessions() {
  const [sessions, setSessions] = useState<TerminalSession[]>([]); const [selected, setSelected] = useState<string>(); const [host, setHost] = useState('192.168.1.1'); const [protocol, setProtocol] = useState<'ssh' | 'telnet' | 'tcp'>('ssh'); const [port, setPort] = useState('22'); const [username, setUsername] = useState('admin'); const [password, setPassword] = useState(''); const [terminalReady, setTerminalReady] = useState(false); const terminalRef = useRef<HTMLDivElement>(null); const termRef = useRef<Terminal>(); const fitRef = useRef<FitAddon>(); const selectedRef = useRef<string>();
  const current = sessions.find((item) => item.id === selected);
  useEffect(() => { void api.getSessions().then((items) => { setSessions(items); if (items[0]) setSelected(items[0].id); }).catch(() => undefined); }, []);
  useEffect(() => { selectedRef.current = selected; }, [selected]);
  useEffect(() => { if (!terminalRef.current) return; const term = new Terminal({ cursorBlink: true, convertEol: true, fontFamily: 'JetBrains Mono, monospace', theme: { background: '#0a101d', foreground: '#d7e2f0', cursor: '#56d6b2' } }); const fit = new FitAddon(); term.loadAddon(fit); term.open(terminalRef.current); fit.fit(); term.writeln('\x1b[36mSentinel terminal\x1b[0m · browser transport'); term.writeln('Create a session; browser terminals use the REST/WebSocket-ready API.'); term.onData((data) => { if (selectedRef.current) void api.terminalWrite(selectedRef.current, data); }); const remove = api.onTerminalData((data) => term.write(data)); termRef.current = term; fitRef.current = fit; setTerminalReady(true); const resize = () => fit.fit(); window.addEventListener('resize', resize); return () => { remove?.(); window.removeEventListener('resize', resize); term.dispose(); }; }, []);
  useEffect(() => { if (!selected || !termRef.current) return; let seen = 0; void api.getSessionHistory(selected).then((history) => { termRef.current?.clear(); history?.forEach((item) => termRef.current?.write(item.data)); seen = history?.length || 0; }).catch(() => undefined); const timer = window.setInterval(() => { void api.getSessionHistory(selected).then((history) => { if (!history || history.length <= seen) return; history.slice(seen).forEach((item) => { if (item.direction === 'in' || item.direction === 'system') termRef.current?.write(item.data); }); seen = history.length; }).catch(() => undefined); }, 1500); return () => window.clearInterval(timer); }, [selected]);
  const connect = async () => { const session = await api.createSession({ host, protocol, port: Number(port), username, password }); setSessions((items) => [session, ...items]); setSelected(session.id); termRef.current?.writeln(`\r\n\x1b[32mSession ${session.name} created.\x1b[0m`); };
  const close = async () => { if (!selected) return; await api.terminalClose(selected); setSessions((items) => items.map((item) => item.id === selected ? { ...item, status: 'closed' } : item)); };
  return <div className="content"><section className="hero-row"><div><p className="muted">Multiple remote sessions · SSH, Telnet, TCP</p><h2>Terminal sessions.</h2></div><a className="secondary button-link" href={api.exportUrl('sessions', 'json')}>Export history</a></section><div className="terminal-layout"><section className="panel session-panel"><div className="panel-heading"><div><h3>Sessions</h3><span className="muted">{sessions.length} active or historical</span></div></div><div className="session-list">{sessions.map((item) => <button key={item.id} className={`session-tab ${selected === item.id ? 'selected' : ''}`} onClick={() => setSelected(item.id)}><span className={`status-dot ${item.status !== 'connected' ? 'offline' : ''}`} /><span><b>{item.name}</b><small>{item.protocol.toUpperCase()} · {item.host}:{item.port}</small></span></button>)}</div><div className="new-session"><h3>New session</h3><label>PROTOCOL<select value={protocol} onChange={(event) => { const value = event.target.value as typeof protocol; setProtocol(value); setPort(value === 'ssh' ? '22' : value === 'telnet' ? '23' : '9000'); }}><option value="ssh">SSH</option><option value="telnet">Telnet</option><option value="tcp">Custom TCP</option></select></label><label>HOST<input value={host} onChange={(event) => setHost(event.target.value)} /></label><label>PORT<input value={port} onChange={(event) => setPort(event.target.value)} /></label>{protocol === 'ssh' && <><label>USERNAME<input value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>PASSWORD<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label></>}<div className="button-row"><button className="secondary" onClick={() => void connect()}>Connect</button>{current && <button className="ghost" onClick={() => void close()}>Close</button>}</div></div></section><section className="panel terminal-panel"><div className="terminal-head"><span><span className={`status-dot ${current?.status !== 'connected' ? 'offline' : ''}`} />{current ? current.host : 'No session selected'}</span><span className="muted">{current ? `${current.protocol.toUpperCase()} · ${current.port}` : 'Ready'}{terminalReady ? '' : ' · loading'}</span></div><div className="terminal-container" ref={terminalRef} onKeyDown={() => undefined} /></section></div></div>;
}

export default App;
